name: fly
on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-fly-crunchy-replicas:
    name: Deploy fly-co-crunchy-replicas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd fly-go-crunchy-replicas && flyctl deploy --remote-only

  deploy-fly-go-neon:
    name: Deploy fly-go-neon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd fly-go-neon && flyctl deploy --remote-only --nixpacks
