name: planetscale

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC

env:
  DATABASE_URL: ${{ secrets.PLANETSCALE_DATABASE_URL }}

jobs:
  wake:
    name: wake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: cd vercel-edge-planetscale && npm i && node lib/wake.js
